package cn.citycraft.JoinMessage;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.bukkit.Bukkit;
import org.bukkit.plugin.PluginManager;
import org.bukkit.plugin.java.JavaPlugin;

import cn.citycraft.JoinMessage.listen.PlayerJoin;

public class Main extends JavaPlugin{
	
	HashMap<String, String[]> msg = new HashMap<String, String[]>();
	List<Map<String, String[]>> perms =  new ArrayList<Map<String, String[]>>();
	
	public boolean authme; 
	
	public void onLoad() {
		this.saveDefaultConfig();
	}

	public void onEnable() {
		this.getLogger().info("登录提示语已加载...");
		PluginManager pm = Bukkit.getPluginManager();
		pm.registerEvents(new PlayerJoin(this), this);
		if (pm.isPluginEnabled("AuthMe")) {
			this.getLogger().info("Find AuthMe Hook...");
			authme = true;
		}
	}
	
}
